site_name: Monarch Ingest
site_url: https://monarch-initiative.github.io/monarch-ingest/
nav:
  - Ingest Tutorial:
    - Configure: tutorials/configure-ingest.md
    - Document: tutorials/add-documentation.md
    - Implement: tutorials/implement-ingest.md
    - Test: tutorials/test-ingest.md
    - Validate: tutorials/validate-output.md
  - Sources:
    - Alliance of Genome Resources: ingests/alliance.md
    - PomBase: ingests/pombase.md
    - XenBase: ingests/xenbase.md
    - ZFIN: ingests/zfin.md
    - SGD: ingests/sgd.md
    - Flybase: ingests/flybase.md
    - RGD: ingests/rgd.md
  - Kozathon:
      - Setup: kozathon/setup.md
theme:
 name: material
markdown_extensions:
  - toc:
      baselevel: 4
