site_name: Monarch Ingest
site_url: https://monarch-initiative.github.io/monarch-ingest/
nav:
  - Ingest Tutorial:
    - Configure: tutorials/configure-ingest.md
    - Document: tutorials/add-documentation.md
    - Implement: tutorials/implement-ingest.md
    - Test: tutorials/test-ingest.md
    - Validate: tutorials/validate-output.md
  - Sources:
    - AGR: ingests/alliance.md
    - PomBase: ingests/pombase.md
    - XenBase: ingests/xenbase.md
    - CTD: ingests/ctd.md
    - ZFIN: ingests/zfin.md
    - HGNC: ingests/hgnc.md
    - SGD: ingests/sgd.md
    - FlyBase: ingests/flybase.md
    - RGD: ingests/rgd.md
    - GO: ingests/goa.md
    - HPO: ingests/hpoa.md
    - MGI: ingests/mgi.md
    - OMIM: ingests/omim.md
    - STRING: ingests/string.md
  - Kozathon:
      - Setup: kozathon/setup.md
theme:
 name: material
markdown_extensions:
  - toc:
      baselevel: 4
