site_name: 'Monarch Ingest Documentation'
site_url: 'https://monarch-initiative.github.io/monarch-ingest/'
repo_name: 'monarch-initiative/monarch-ingest'
repo_url: 'https://github.com/monarch-initiative/monarch-ingest'


nav:
  - Welcome: 'index.md'
  - CLI: 'CLI.md'
  - Creating an Ingest: 
    - What is an Ingest?: 'Create-an-Ingest/index.md'
    - Propose: 'Create-an-Ingest/1. Propose.md'
    - Configure: 'Create-an-Ingest/2. Configure.md'
    - Document: 'Create-an-Ingest/3. Document.md'
    - Implement: 'Create-an-Ingest/4. Implement.md'
    - Testing: 'Create-an-Ingest/5. Test.md'
  - KG Build Process: 'KG-Build-Process/kg-build-process.md'
  - Principles: 'Principles/modeling-principles.md'
  - Sources:
    - Alliance: 'Sources/Alliance.md'
    - BGee: 'Sources/BGee.md'
    - CTD: 'Sources/CTD.md'
    - Dictybase: 'Sources/Dictybase.md'
    - Flybase: 'Sources/Flybase.md'
    - GOA: 'Sources/GOA.md'
    - HGNC: 'Sources/HGNC.md'
    - HPOA: 'Sources/HPOA.md'
    - MGI: 'Sources/MGI.md'
    - NCBI: 'Sources/NCBI.md'
    - OMIM: 'Sources/OMIM.md'
    - Panther: 'Sources/Panther.md'
    - Pombase: 'Sources/Pombase.md'
    - Reactome: 'Sources/Reactome.md'
    - RGD: 'Sources/RGD.md'
    - SGD: 'Sources/SGD.md'
    - String: 'Sources/String.md'
    - Xenbase: 'Sources/Xenbase.md'
    - ZFIN: 'Sources/ZFIN.md'


theme:
    name: 'material'
    docs_dir: docs/
    logo: 'images/monarch-initiative.png'
    favicon: 'images/favicon.ico'
    features:
        - navigation.expand
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
    palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    font:
        text: 'Source Sans Pro'
        code: 'Source Sans Pro Mono'


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [ ./src/monarch_ingest ]
          import:
          - https://docs.python.org/3/objects.inv
          - https://mkdocstrings.github.io/objects.inv
          - https://mkdocstrings.github.io/griffe/objects.inv
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: yes
            merge_init_into_class: yes
            # separate_signature: yes
            show_signature: no
            show_source: no
            show_root_full_path: no
            show_root_toc_entry: False
            filters:
              - "!^_[^_]"
              - "^_[^_]"


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
      

extra:
  social:
    - icon: 'fontawesome/solid/house'
      link: 'https://monarchinitiative.org'
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/monarch-initiative'

