[tool.poetry]
name = "monarch-ingest"
version = "0.1.2"
description = ""
authors = [
    "Kevin Schaper <kevinschaper@gmail.com>",
    "Victoria Soesanto <victoria.soesanto@cuanschutz.edu>",
    "Kent Shefchek <kent@tislab.org>",
    "Glass Elsarboukh <g.elsarboukh@gmail.com>",
    "The Monarch Initiative <info@monarchinitiative.org>"
]

[tool.poetry.dependencies]
python = "^3.8"
importlib-metadata = "^4.6.1"
koza = "^0.1.11"
biolink_model_pydantic = "^0.1.7"
kghub-downloader = "0.1.14"
kgx = "^1.5.6"
prefect = "2.0b2"
greenlet = "^1.1.2"
typer = "0.4"
linkml = "^1.2.7"

[tool.poetry.dev-dependencies]
autoflake = "^1.4"
flake8 = "^3.9.2"
isort = "^5.9.1"
mkdocs = "^1.2.2"
mkdocs-material = "^7.2.4"
pytest = "^7.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line_length = 90
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 90
multi_line_output = 3
include_trailing_comma = true