[tool.poetry]
name = "monarch-ingest"
version = "0.1.0"
description = ""
authors = ["Kevin Schaper <kevinschaper@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
koza = "^0.0.1-alpha.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
