[tool.poetry]
name = "monarch-ingest"
version = "0.8.0"
description = ""
authors = [
    "The Monarch Initiative <info@monarchinitiative.org>",
    "Kevin Schaper <kevinschaper@gmail.com>",
    "Victoria Soesanto <victoria.soesanto@cuanschutz.edu>",
    "Glass Elsarboukh <g.elsarboukh@gmail.com>",
    "Kent Shefchek <kent@tislab.org>",
    "Richard Bruskiewich <richard.bruskiewich@delphinai.com>",
]
packages = [
    { include = "monarch_ingest", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
# Monarch & Related Dependencies
biolink-model = { git = "https://github.com/glass-ships/biolink-model/", branch = "dependencies" } # "^3.5.5"
bmt = "^1.0.15"
cat-merge = ">=0.2.0"
closurizer = "0.4.1"
kghub-downloader = "^0.3.2"
kgx = { git = "https://github.com/biolink/kgx", branch = "master" } # ">=2.1"
koza = "^0.5"
linkml = "^1.6.3"
linkml-runtime = "1.6.2"
linkml-solr = {git = "https://github.com/linkml/linkml-solr.git", branch = "main"} # "^0.1.3"
multi-indexer = "0.0.5"
# Other Dependencies
botocore = "^1.31"
importlib-metadata = ">=4.6.1"
loguru = "*"
pydantic = "^2.5"
sh = "^1.14.3"
typer = "^0.7"
typer-cli = "^0.0.13"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.1"
mkdocs = "^1.3.0"
mkdocs-material = "^8.2.9"
black = "^23.10.0"
ruff = "*"

[tool.poetry.scripts]
ingest = "monarch_ingest.main:typer_app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line_length = 120
skip-string-normalization = true

[tool.ruff]
line-length = 120
ignore = [
    "F541", # f-strings with no placeholders
]