[tool.poetry]
name = "monarch-ingest"
version = "0.2.0"
description = ""
authors = [
    "Kevin Schaper <kevinschaper@gmail.com>",
    "Victoria Soesanto <victoria.soesanto@cuanschutz.edu>",
    "Glass Elsarboukh <g.elsarboukh@gmail.com>",
    "Kent Shefchek <kent@tislab.org>",
    "The Monarch Initiative <info@monarchinitiative.org>"
]

[tool.poetry.dependencies]
python = "^3.8"
importlib-metadata = "^4.6.1"
koza = "^0.1.11"
biolink_model_pydantic = "^0.1.11"
kghub-downloader = "0.1.14"
kgx = "^1.5.6"
greenlet = "^1.1.2"
typer = "^0.4"

[tool.poetry.dev-dependencies]
autoflake = "^1.4"
flake8 = "^3.9.2"
isort = "^5.9.1"
mkdocs = "^1.3.0"
mkdocs-material = "^8.2.9"
pytest = "^7.1.1"

[tool.poetry.scripts]
ingest = "monarch_ingest:main.typer_app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line_length = 90
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 90
multi_line_output = 3
include_trailing_comma = true
